from decimal import Decimal

TAX_RATE = Decimal("0.16")

SPECIALTIES = [
    "Medicina General",
    "Cardiologia",
    "Neumologia",
    "Gastroenterologia",
    "Traumatologia",
    "Dermatologia",
    "Otorrinolaringologia",
    "Oftalmologia",
    "Ginecologia",
    "Pediatria",
    "Endocrinologia",
    "Neurologia",
    "Psiquiatria",
    "Urologia",
    "Oncologia",
    "Cirugia General",
    "Hematologia",
    "Alergologia",
    "Reumatologia",
]

INSURANCE_PROVIDERS = [
    ("GNP Seguros", "GNP", True),
    ("Seguros Atlas", "SATL", True),
    ("Qualitas", "QUAL", True),
    ("AXA Seguros", "AXA", True),
    ("MetLife Mexico", "METL", True),
    ("Banorte Seguros", "BNTE", True),
    ("Primer Seguros", "PRIM", True),
    ("Mapfre Mexico", "MAPF", True),
    ("Zurich Mexico", "ZRCH", True),
    ("Allianz Mexico", "ALNZ", True),
    ("HDI Seguros", "HDI", True),
    ("Latin American Seguros", "LAS", False),
]

COVERAGE_PERCENTAGES = [50, 60, 70, 80, 90, 100]

BLOOD_TYPES = ["O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-"]
BLOOD_TYPE_WEIGHTS = [45, 8, 35, 4, 12, 2, 4, 1]

ALLERGIES_POOL = [
    "Penicilina y derivados",
    "Ibuprofeno y AINEs",
    "Sulfonamidas",
    "Latex",
    "Contraste yodado",
    "Lidocaina",
    "Codeina y opioides",
    "Aspirina (acido acetilsalicilico)",
    "Amoxicilina",
    "Cefalexina",
    "Dipirona metamizol",
    "Gluten (enfermedad celiaca)",
    "Lactosa (intolerancia)",
    "Mariscos (camarones, langosta)",
    "Huevo",
    "Polvo y acaros",
    "Polen",
    "Picadura de abeja",
    "Nitrofurantoina",
    "Ciprofloxacino",
    "Metformina",
    "Enalapril",
    "Losartan",
    "Diclofenaco",
    "Prednisona",
]

DURATION_MINUTES_BY_SPECIALTY = {
    "Medicina General": [20, 30, 30],
    "Cardiologia": [30, 30, 45],
    "Neumologia": [30, 30, 45],
    "Gastroenterologia": [30, 30, 45],
    "Traumatologia": [20, 30, 30],
    "Dermatologia": [15, 20, 20],
    "Otorrinolaringologia": [20, 30, 30],
    "Oftalmologia": [20, 30, 30],
    "Ginecologia": [30, 30, 45],
    "Pediatria": [20, 30, 30],
    "Endocrinologia": [30, 30, 45],
    "Neurologia": [30, 30, 45],
    "Psiquiatria": [45, 45, 60],
    "Urologia": [30, 30, 30],
    "Oncologia": [30, 45, 45],
    "Cirugia General": [30, 30, 45],
    "Hematologia": [30, 30, 45],
    "Alergologia": [20, 30, 30],
    "Reumatologia": [30, 30, 45],
}

DOSAGE_TEMPLATES = [
    "500mg cada 8 horas",
    "250mg cada 12 horas",
    "1g cada 6 horas",
    "400mg cada 8 horas",
    "100mg cada 12 horas",
    "10mg una vez al dia",
    "20mg cada 12 horas",
    "5mg una vez al dia",
    "50mg cada 8 horas",
    "200mg cada 8 horas",
    "300mg una vez al dia",
    "150mg cada 12 horas",
    "80mg cada 8 horas",
    "600mg cada 12 horas",
    "125mg cada 8 horas",
    "0.5mg una vez al dia",
    "25mg cada 12 horas",
    "75mg una vez al dia",
    "500mg cada 6 horas",
    "1000mg cada 12 horas",
]

FREQUENCY_TEMPLATES = [
    "cada 8 horas por 7 dias",
    "cada 12 horas por 10 dias",
    "cada 24 horas por 5 dias",
    "cada 6 horas por 7 dias",
    "cada 8 horas por 14 dias",
    "cada 12 horas por 7 dias",
    "una vez al dia por 30 dias",
    "cada 8 horas por 5 dias",
    "cada 24 horas por 14 dias",
    "cada 12 horas por 21 dias",
    "cada 8 horas por 10 dias",
    "cada 6 horas por 5 dias",
    "dos veces al dia por 7 dias",
    "tres veces al dia por 5 dias",
    "una vez al dia por 7 dias",
    "cada 48 horas por 5 dosis",
    "cada semana por 4 semanas",
    "una vez al dia por 90 dias",
    "cada 12 horas por 5 dias",
    "cada 8 horas por 3 dias",
]

INSTRUCTION_TEMPLATES = [
    "Tomar con alimentos",
    "Tomar en ayunas",
    "Tomar despues de las comidas",
    "Tomar con abundante agua",
    "Evitar consumo de alcohol",
    "No suspender sin indicacion medica",
    "Tomar con un vaso lleno de agua",
    "Evitar exposicion prolongada al sol",
    "Mantener refrigerado",
    "Agitar bien antes de usar",
    None,
    None,
    None,
]
